services:
  discord-terminal-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-terminal-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1       # Ensures logs appear in 'docker logs' immediately
      - LOADING_TIMEOUT=5        # Time in seconds before showing the loading message
      - DETECT_DUPLICATES=True   # Set to False to disable console warnings
    volumes:
      - shared-commands:/app/commands  # The bot reads from here
#      - ./bot.py:/app/bot.py     # Mount just the script
#      - ./lib:/app/lib           # Mount the lib folder
#      - ./commands:/app/commands # Mount the config/scripts folder
      - /var/run/docker.sock:/var/run/docker.sock # The "Magic" Bridge
      - /var/lib/docker/containers:/app/dcon:ro
#      - ./data/config.txt:/app/data/config.txt:ro
    user: root                   # Required to have permission to use the socket

  discord-terminal-bot-editor:
    build:
      context: ./editor
      dockerfile: Dockerfile
    container_name: discord-terminal-bot-editor
    ports:
      - "1701:80"
    volumes:
      - shared-commands:/app/commands  # The editor writes to here
#      - ./commands:/app/commands
    restart: always
    env_file:
      - .env


volumes:
  shared-commands:
